// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: desmos/posts/v1beta1/posts.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Post contains all the data of a Desmos post
type Post struct {
	PostID         string       `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"id" yaml"id"`
	ParentID       string       `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id" yaml"parent_id"`
	Message        string       `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty" yaml"message"`
	Created        time.Time    `protobuf:"bytes,4,opt,name=created,proto3,stdtime" json:"created" yaml"created"`
	LastEdited     time.Time    `protobuf:"bytes,5,opt,name=last_edited,json=lastEdited,proto3,stdtime" json:"last_edited" yaml"created"`
	AllowsComments bool         `protobuf:"varint,6,opt,name=allows_comments,json=allowsComments,proto3" json:"allows_comments" yaml"allows_comments"`
	Subspace       string       `protobuf:"bytes,7,opt,name=subspace,proto3" json:"subspace,omitempty" yaml"subspace"`
	OptionalData   OptionalData `protobuf:"bytes,8,rep,name=optional_data,json=optionalData,proto3,castrepeated=OptionalData" json:"optional_data,omitempty" yaml"optional_data,omitempty"`
	Creator        string       `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty" yaml"creator"`
	Attachments    Attachments  `protobuf:"bytes,10,rep,name=attachments,proto3,castrepeated=Attachments" json:"attachments" yaml"attachments,omitempty"`
	PollData       *PollData    `protobuf:"bytes,11,opt,name=poll_data,json=pollData,proto3" json:"poll_data,omitempty" yaml"poll_data,omitempty"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_46085d0cf4c5bade, []int{0}
}
func (m *Post) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Post.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return m.Size()
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetPostID() string {
	if m != nil {
		return m.PostID
	}
	return ""
}

func (m *Post) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *Post) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Post) GetCreated() time.Time {
	if m != nil {
		return m.Created
	}
	return time.Time{}
}

func (m *Post) GetLastEdited() time.Time {
	if m != nil {
		return m.LastEdited
	}
	return time.Time{}
}

func (m *Post) GetAllowsComments() bool {
	if m != nil {
		return m.AllowsComments
	}
	return false
}

func (m *Post) GetSubspace() string {
	if m != nil {
		return m.Subspace
	}
	return ""
}

func (m *Post) GetOptionalData() OptionalData {
	if m != nil {
		return m.OptionalData
	}
	return nil
}

func (m *Post) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Post) GetAttachments() Attachments {
	if m != nil {
		return m.Attachments
	}
	return nil
}

func (m *Post) GetPollData() *PollData {
	if m != nil {
		return m.PollData
	}
	return nil
}

// Attachment contains the information representing any type of file provided with a post.
// This file can be an image or a multimedia file (vocals, video, documents, etc.).
type Attachment struct {
	URI      string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri" yaml"uri"`
	MimeType string   `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type" yaml"mime_type"`
	Tags     []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" yaml"tags,omitempty"`
}

func (m *Attachment) Reset()         { *m = Attachment{} }
func (m *Attachment) String() string { return proto.CompactTextString(m) }
func (*Attachment) ProtoMessage()    {}
func (*Attachment) Descriptor() ([]byte, []int) {
	return fileDescriptor_46085d0cf4c5bade, []int{1}
}
func (m *Attachment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Attachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Attachment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Attachment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attachment.Merge(m, src)
}
func (m *Attachment) XXX_Size() int {
	return m.Size()
}
func (m *Attachment) XXX_DiscardUnknown() {
	xxx_messageInfo_Attachment.DiscardUnknown(m)
}

var xxx_messageInfo_Attachment proto.InternalMessageInfo

func (m *Attachment) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

func (m *Attachment) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

func (m *Attachment) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

// OptionalDataEntry represents a Posts' optional data entry and allows for custom
// Amino and JSON serialization and deserialization.
type OptionalDataEntry struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *OptionalDataEntry) Reset()         { *m = OptionalDataEntry{} }
func (m *OptionalDataEntry) String() string { return proto.CompactTextString(m) }
func (*OptionalDataEntry) ProtoMessage()    {}
func (*OptionalDataEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_46085d0cf4c5bade, []int{2}
}
func (m *OptionalDataEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OptionalDataEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OptionalDataEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OptionalDataEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptionalDataEntry.Merge(m, src)
}
func (m *OptionalDataEntry) XXX_Size() int {
	return m.Size()
}
func (m *OptionalDataEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_OptionalDataEntry.DiscardUnknown(m)
}

var xxx_messageInfo_OptionalDataEntry proto.InternalMessageInfo

func (m *OptionalDataEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *OptionalDataEntry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type QueryPostsParams struct {
	Page         int32      `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit        int32      `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy       string     `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder    string     `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	ParentID     string     `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CreationTime *time.Time `protobuf:"bytes,6,opt,name=creation_time,json=creationTime,proto3,stdtime" json:"creation_time,omitempty"`
	Subspace     string     `protobuf:"bytes,7,opt,name=subspace,proto3" json:"subspace,omitempty"`
	Creator      string     `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
	Hashtags     []string   `protobuf:"bytes,9,rep,name=hashtags,proto3" json:"hashtags,omitempty"`
}

func (m *QueryPostsParams) Reset()         { *m = QueryPostsParams{} }
func (m *QueryPostsParams) String() string { return proto.CompactTextString(m) }
func (*QueryPostsParams) ProtoMessage()    {}
func (*QueryPostsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_46085d0cf4c5bade, []int{3}
}
func (m *QueryPostsParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPostsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPostsParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPostsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPostsParams.Merge(m, src)
}
func (m *QueryPostsParams) XXX_Size() int {
	return m.Size()
}
func (m *QueryPostsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPostsParams.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPostsParams proto.InternalMessageInfo

func (m *QueryPostsParams) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *QueryPostsParams) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QueryPostsParams) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *QueryPostsParams) GetSortOrder() string {
	if m != nil {
		return m.SortOrder
	}
	return ""
}

func (m *QueryPostsParams) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *QueryPostsParams) GetCreationTime() *time.Time {
	if m != nil {
		return m.CreationTime
	}
	return nil
}

func (m *QueryPostsParams) GetSubspace() string {
	if m != nil {
		return m.Subspace
	}
	return ""
}

func (m *QueryPostsParams) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *QueryPostsParams) GetHashtags() []string {
	if m != nil {
		return m.Hashtags
	}
	return nil
}

func init() {
	proto.RegisterType((*Post)(nil), "desmos.posts.v1beta1.Post")
	proto.RegisterType((*Attachment)(nil), "desmos.posts.v1beta1.Attachment")
	proto.RegisterType((*OptionalDataEntry)(nil), "desmos.posts.v1beta1.OptionalDataEntry")
	proto.RegisterType((*QueryPostsParams)(nil), "desmos.posts.v1beta1.QueryPostsParams")
}

func init() { proto.RegisterFile("desmos/posts/v1beta1/posts.proto", fileDescriptor_46085d0cf4c5bade) }

var fileDescriptor_46085d0cf4c5bade = []byte{
	// 857 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xbd, 0x92, 0xdb, 0x36,
	0x10, 0x3e, 0x9e, 0xfe, 0x48, 0xe8, 0xce, 0x3f, 0x98, 0xcb, 0x98, 0x96, 0x73, 0x82, 0x86, 0x4d,
	0x94, 0xf1, 0x99, 0x1a, 0x5f, 0x26, 0x4d, 0xba, 0x30, 0x56, 0xa1, 0x22, 0x73, 0x0a, 0xc6, 0x4e,
	0xe1, 0x46, 0x03, 0x89, 0x88, 0x8e, 0x13, 0x52, 0xe0, 0x10, 0xd0, 0x25, 0x7c, 0x0b, 0xa7, 0x4b,
	0x95, 0x71, 0x9d, 0x27, 0x48, 0x95, 0xda, 0xa5, 0xcb, 0x54, 0x70, 0x46, 0xd7, 0x64, 0xae, 0xe4,
	0x13, 0x64, 0x00, 0x50, 0x14, 0xad, 0x9c, 0xd3, 0xb8, 0xc3, 0x7e, 0xfb, 0xed, 0x07, 0xee, 0x62,
	0x77, 0x09, 0x06, 0x21, 0xe5, 0x09, 0xe3, 0xa3, 0x94, 0x71, 0xc1, 0x47, 0x57, 0x4f, 0xe7, 0x54,
	0x90, 0xa7, 0xc6, 0xf2, 0xd3, 0x8c, 0x09, 0x06, 0x4f, 0x0c, 0xc3, 0x37, 0x58, 0xc9, 0xe8, 0x9d,
	0x2c, 0xd9, 0x92, 0x69, 0xc2, 0x48, 0x9d, 0x0c, 0xb7, 0x87, 0x96, 0x8c, 0x2d, 0x63, 0x3a, 0xd2,
	0xd6, 0x7c, 0xfd, 0xc3, 0x48, 0x44, 0x09, 0xe5, 0x82, 0x24, 0x69, 0x49, 0xf8, 0xd0, 0x75, 0x71,
	0x5c, 0x5e, 0xe7, 0xfd, 0xd2, 0x01, 0xcd, 0x29, 0xe3, 0x02, 0x7e, 0x09, 0x3a, 0x8a, 0x35, 0x8b,
	0x42, 0xd7, 0x1a, 0x58, 0x43, 0x27, 0xf8, 0x74, 0x23, 0x51, 0x5b, 0xb9, 0x26, 0xcf, 0x6e, 0x24,
	0x3a, 0x8c, 0xc2, 0x42, 0x22, 0x3b, 0x27, 0x49, 0xec, 0x45, 0xa1, 0x87, 0xdb, 0x8a, 0x3c, 0x09,
	0xe1, 0x04, 0x38, 0x29, 0xc9, 0xe8, 0x4a, 0x07, 0x1e, 0xea, 0xc0, 0xb3, 0x8d, 0x44, 0xf6, 0x54,
	0x83, 0x3a, 0x74, 0x47, 0x28, 0x24, 0xba, 0xab, 0x15, 0x2a, 0xc4, 0xc3, 0xb6, 0x39, 0x4f, 0x42,
	0xf8, 0x18, 0x74, 0x12, 0xca, 0x39, 0x59, 0x52, 0xb7, 0xa1, 0x85, 0xee, 0x17, 0x12, 0x1d, 0x6b,
	0x7e, 0x89, 0x7b, 0x78, 0xcb, 0x80, 0x17, 0xa0, 0xb3, 0xc8, 0x28, 0x11, 0x34, 0x74, 0x9b, 0x03,
	0x6b, 0xd8, 0x3d, 0xef, 0xf9, 0xa6, 0x18, 0xfe, 0xb6, 0x18, 0xfe, 0xf3, 0x6d, 0x31, 0x82, 0x87,
	0x6f, 0x24, 0x3a, 0xa8, 0xc4, 0xca, 0x38, 0xef, 0xd5, 0x3b, 0x64, 0xe1, 0xad, 0x0a, 0xfc, 0x1e,
	0x74, 0x63, 0xc2, 0xc5, 0x8c, 0x86, 0x91, 0x12, 0x6d, 0x7d, 0x8c, 0x28, 0x50, 0x4a, 0x63, 0x2d,
	0x04, 0x5f, 0x80, 0xbb, 0x24, 0x8e, 0xd9, 0x4f, 0x7c, 0xb6, 0x60, 0x49, 0x42, 0x57, 0x82, 0xbb,
	0xed, 0x81, 0x35, 0xb4, 0x83, 0xb3, 0x1b, 0x89, 0xf6, 0x5d, 0x85, 0x44, 0x9f, 0x68, 0xb9, 0x3d,
	0xdc, 0xc3, 0x77, 0x0c, 0xf2, 0x4d, 0x09, 0x40, 0x1f, 0xd8, 0x7c, 0x3d, 0xe7, 0x29, 0x59, 0x50,
	0xb7, 0xa3, 0xab, 0x05, 0x0b, 0x89, 0xee, 0xe8, 0xe0, 0xad, 0xc3, 0xc3, 0x15, 0x07, 0xfe, 0x66,
	0x81, 0x63, 0x96, 0x8a, 0x88, 0xad, 0x48, 0x3c, 0x0b, 0x89, 0x20, 0xae, 0x3d, 0x68, 0x0c, 0xbb,
	0xe7, 0x9f, 0xf9, 0xb7, 0xf5, 0x9b, 0x7f, 0x51, 0x52, 0x9f, 0x11, 0x41, 0xc6, 0x2b, 0x91, 0xe5,
	0xc1, 0x54, 0xa5, 0x7b, 0x23, 0xd1, 0x83, 0xf7, 0x54, 0xce, 0x58, 0x12, 0x09, 0x9a, 0xa4, 0x22,
	0x2f, 0x24, 0x3a, 0xd5, 0xb7, 0x7f, 0xc0, 0xef, 0xfd, 0xfe, 0x0e, 0x1d, 0xd5, 0x65, 0xf1, 0x11,
	0xab, 0x59, 0xea, 0xf5, 0x75, 0x0d, 0x59, 0xe6, 0x3a, 0x7b, 0xaf, 0x5f, 0xe2, 0x1e, 0xde, 0x32,
	0xe0, 0x15, 0xe8, 0x12, 0x21, 0xc8, 0xe2, 0xd2, 0x14, 0x14, 0xe8, 0x54, 0x06, 0xb7, 0xa7, 0xf2,
	0x75, 0x45, 0x0c, 0xce, 0xcb, 0x27, 0x7b, 0x64, 0x6a, 0xbc, 0x53, 0x78, 0xff, 0x33, 0xbb, 0xbb,
	0x10, 0x8e, 0xeb, 0x17, 0xc1, 0x97, 0xc0, 0x51, 0xc3, 0x63, 0x0a, 0xd8, 0xd5, 0x2d, 0xd2, 0xbf,
	0xfd, 0xd6, 0x29, 0x8b, 0x75, 0x5e, 0xc1, 0x69, 0x21, 0xd1, 0x43, 0xd3, 0xf4, 0xdb, 0xc8, 0xda,
	0x6d, 0xd8, 0x4e, 0x4b, 0xe2, 0x57, 0xf6, 0xaf, 0xaf, 0x91, 0xf5, 0xcf, 0x6b, 0x64, 0x79, 0x7f,
	0x5a, 0x00, 0xec, 0x3e, 0x01, 0x3e, 0x01, 0x8d, 0x75, 0x16, 0x95, 0x53, 0xf9, 0x68, 0x23, 0x51,
	0xe3, 0x05, 0x9e, 0xdc, 0x48, 0xa4, 0xd0, 0x42, 0x22, 0x47, 0x8b, 0xaf, 0xb3, 0xc8, 0xc3, 0x0a,
	0x51, 0x13, 0x99, 0x44, 0x09, 0x9d, 0x89, 0x3c, 0xa5, 0xf5, 0x89, 0xfc, 0x36, 0x4a, 0xe8, 0xf3,
	0x3c, 0xa5, 0x6a, 0x22, 0x2b, 0x42, 0x35, 0x91, 0x15, 0xe2, 0x61, 0x3b, 0x29, 0x99, 0xf0, 0x0c,
	0x34, 0x05, 0x59, 0x72, 0xb7, 0x31, 0x68, 0x0c, 0x9d, 0xc0, 0x2d, 0x24, 0x3a, 0xd1, 0x64, 0x05,
	0xd6, 0x93, 0xd0, 0xac, 0x5a, 0x02, 0x63, 0x70, 0xff, 0x3f, 0x0d, 0x04, 0xef, 0x81, 0xc6, 0x8f,
	0x34, 0x37, 0x69, 0x60, 0x75, 0x84, 0x27, 0xa0, 0x75, 0x45, 0xe2, 0x75, 0xf9, 0x95, 0xd8, 0x18,
	0x35, 0x99, 0x3f, 0x0e, 0xc1, 0xbd, 0xef, 0xd6, 0x34, 0xcb, 0xd5, 0x16, 0xe2, 0x53, 0x92, 0x91,
	0x84, 0x43, 0x08, 0x9a, 0xa9, 0x5a, 0x11, 0x4a, 0xa7, 0x85, 0xf5, 0x59, 0x09, 0xc5, 0x51, 0x12,
	0x09, 0x2d, 0xd4, 0xc2, 0xc6, 0x80, 0x0f, 0x40, 0x87, 0xb3, 0x4c, 0xcc, 0xe6, 0xb9, 0xd9, 0x27,
	0xb8, 0xad, 0xcc, 0x20, 0x87, 0xa7, 0x00, 0x68, 0x07, 0xcb, 0x42, 0x9a, 0xe9, 0xf5, 0xe1, 0x60,
	0x47, 0x21, 0x17, 0x0a, 0x80, 0x9f, 0xd7, 0x57, 0x5a, 0x4b, 0x17, 0xf0, 0xa8, 0xbe, 0xd2, 0x6a,
	0x2b, 0x6b, 0x0c, 0x8e, 0x75, 0x4b, 0x46, 0x6c, 0x35, 0x53, 0xbb, 0x57, 0x8f, 0xf6, 0xff, 0xaf,
	0x8d, 0xa6, 0xde, 0x10, 0x47, 0xdb, 0x30, 0xe5, 0x80, 0xbd, 0xfd, 0x61, 0xae, 0x0d, 0xae, 0xbb,
	0x9b, 0x0b, 0x5b, 0xbb, 0xaa, 0x21, 0xe8, 0x01, 0xfb, 0x92, 0xf0, 0x4b, 0xfd, 0x42, 0x8e, 0x7a,
	0x21, 0x5c, 0xd9, 0xc1, 0xf8, 0xcd, 0xa6, 0x6f, 0xbd, 0xdd, 0xf4, 0xad, 0xbf, 0x37, 0x7d, 0xeb,
	0xd5, 0x75, 0xff, 0xe0, 0xed, 0x75, 0xff, 0xe0, 0xaf, 0xeb, 0xfe, 0xc1, 0xcb, 0xc7, 0xcb, 0x48,
	0x5c, 0xae, 0xe7, 0xfe, 0x82, 0x25, 0x23, 0xd3, 0xb9, 0x4f, 0x62, 0x32, 0xe7, 0xe5, 0x79, 0xf4,
	0x73, 0xf9, 0xaf, 0x50, 0xad, 0xc0, 0xe7, 0x6d, 0x9d, 0xc0, 0x17, 0xff, 0x06, 0x00, 0x00, 0xff,
	0xff, 0xfb, 0x51, 0x11, 0xc6, 0xb7, 0x06, 0x00, 0x00,
}

func (this *Post) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Post)
	if !ok {
		that2, ok := that.(Post)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.PostID != that1.PostID {
		return false
	}
	if this.ParentID != that1.ParentID {
		return false
	}
	if this.Message != that1.Message {
		return false
	}
	if !this.Created.Equal(that1.Created) {
		return false
	}
	if !this.LastEdited.Equal(that1.LastEdited) {
		return false
	}
	if this.AllowsComments != that1.AllowsComments {
		return false
	}
	if this.Subspace != that1.Subspace {
		return false
	}
	if len(this.OptionalData) != len(that1.OptionalData) {
		return false
	}
	for i := range this.OptionalData {
		if !this.OptionalData[i].Equal(&that1.OptionalData[i]) {
			return false
		}
	}
	if this.Creator != that1.Creator {
		return false
	}
	if len(this.Attachments) != len(that1.Attachments) {
		return false
	}
	for i := range this.Attachments {
		if !this.Attachments[i].Equal(&that1.Attachments[i]) {
			return false
		}
	}
	if !this.PollData.Equal(that1.PollData) {
		return false
	}
	return true
}
func (this *Attachment) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Attachment)
	if !ok {
		that2, ok := that.(Attachment)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.URI != that1.URI {
		return false
	}
	if this.MimeType != that1.MimeType {
		return false
	}
	if len(this.Tags) != len(that1.Tags) {
		return false
	}
	for i := range this.Tags {
		if this.Tags[i] != that1.Tags[i] {
			return false
		}
	}
	return true
}
func (this *OptionalDataEntry) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*OptionalDataEntry)
	if !ok {
		that2, ok := that.(OptionalDataEntry)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Key != that1.Key {
		return false
	}
	if this.Value != that1.Value {
		return false
	}
	return true
}
func (m *Post) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Post) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Post) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PollData != nil {
		{
			size, err := m.PollData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPosts(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Attachments) > 0 {
		for iNdEx := len(m.Attachments) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attachments[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPosts(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintPosts(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.OptionalData) > 0 {
		for iNdEx := len(m.OptionalData) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OptionalData[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPosts(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.Subspace) > 0 {
		i -= len(m.Subspace)
		copy(dAtA[i:], m.Subspace)
		i = encodeVarintPosts(dAtA, i, uint64(len(m.Subspace)))
		i--
		dAtA[i] = 0x3a
	}
	if m.AllowsComments {
		i--
		if m.AllowsComments {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.LastEdited, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.LastEdited):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintPosts(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x2a
	n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.Created, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.Created):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintPosts(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x22
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintPosts(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ParentID) > 0 {
		i -= len(m.ParentID)
		copy(dAtA[i:], m.ParentID)
		i = encodeVarintPosts(dAtA, i, uint64(len(m.ParentID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PostID) > 0 {
		i -= len(m.PostID)
		copy(dAtA[i:], m.PostID)
		i = encodeVarintPosts(dAtA, i, uint64(len(m.PostID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Attachment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Attachment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Attachment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Tags) > 0 {
		for iNdEx := len(m.Tags) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Tags[iNdEx])
			copy(dAtA[i:], m.Tags[iNdEx])
			i = encodeVarintPosts(dAtA, i, uint64(len(m.Tags[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.MimeType) > 0 {
		i -= len(m.MimeType)
		copy(dAtA[i:], m.MimeType)
		i = encodeVarintPosts(dAtA, i, uint64(len(m.MimeType)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.URI) > 0 {
		i -= len(m.URI)
		copy(dAtA[i:], m.URI)
		i = encodeVarintPosts(dAtA, i, uint64(len(m.URI)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OptionalDataEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OptionalDataEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OptionalDataEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintPosts(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintPosts(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPostsParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPostsParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPostsParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hashtags) > 0 {
		for iNdEx := len(m.Hashtags) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Hashtags[iNdEx])
			copy(dAtA[i:], m.Hashtags[iNdEx])
			i = encodeVarintPosts(dAtA, i, uint64(len(m.Hashtags[iNdEx])))
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintPosts(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Subspace) > 0 {
		i -= len(m.Subspace)
		copy(dAtA[i:], m.Subspace)
		i = encodeVarintPosts(dAtA, i, uint64(len(m.Subspace)))
		i--
		dAtA[i] = 0x3a
	}
	if m.CreationTime != nil {
		n4, err4 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CreationTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreationTime):])
		if err4 != nil {
			return 0, err4
		}
		i -= n4
		i = encodeVarintPosts(dAtA, i, uint64(n4))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ParentID) > 0 {
		i -= len(m.ParentID)
		copy(dAtA[i:], m.ParentID)
		i = encodeVarintPosts(dAtA, i, uint64(len(m.ParentID)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SortOrder) > 0 {
		i -= len(m.SortOrder)
		copy(dAtA[i:], m.SortOrder)
		i = encodeVarintPosts(dAtA, i, uint64(len(m.SortOrder)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SortBy) > 0 {
		i -= len(m.SortBy)
		copy(dAtA[i:], m.SortBy)
		i = encodeVarintPosts(dAtA, i, uint64(len(m.SortBy)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Limit != 0 {
		i = encodeVarintPosts(dAtA, i, uint64(m.Limit))
		i--
		dAtA[i] = 0x10
	}
	if m.Page != 0 {
		i = encodeVarintPosts(dAtA, i, uint64(m.Page))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPosts(dAtA []byte, offset int, v uint64) int {
	offset -= sovPosts(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Post) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PostID)
	if l > 0 {
		n += 1 + l + sovPosts(uint64(l))
	}
	l = len(m.ParentID)
	if l > 0 {
		n += 1 + l + sovPosts(uint64(l))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovPosts(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.Created)
	n += 1 + l + sovPosts(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.LastEdited)
	n += 1 + l + sovPosts(uint64(l))
	if m.AllowsComments {
		n += 2
	}
	l = len(m.Subspace)
	if l > 0 {
		n += 1 + l + sovPosts(uint64(l))
	}
	if len(m.OptionalData) > 0 {
		for _, e := range m.OptionalData {
			l = e.Size()
			n += 1 + l + sovPosts(uint64(l))
		}
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovPosts(uint64(l))
	}
	if len(m.Attachments) > 0 {
		for _, e := range m.Attachments {
			l = e.Size()
			n += 1 + l + sovPosts(uint64(l))
		}
	}
	if m.PollData != nil {
		l = m.PollData.Size()
		n += 1 + l + sovPosts(uint64(l))
	}
	return n
}

func (m *Attachment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.URI)
	if l > 0 {
		n += 1 + l + sovPosts(uint64(l))
	}
	l = len(m.MimeType)
	if l > 0 {
		n += 1 + l + sovPosts(uint64(l))
	}
	if len(m.Tags) > 0 {
		for _, s := range m.Tags {
			l = len(s)
			n += 1 + l + sovPosts(uint64(l))
		}
	}
	return n
}

func (m *OptionalDataEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovPosts(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovPosts(uint64(l))
	}
	return n
}

func (m *QueryPostsParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Page != 0 {
		n += 1 + sovPosts(uint64(m.Page))
	}
	if m.Limit != 0 {
		n += 1 + sovPosts(uint64(m.Limit))
	}
	l = len(m.SortBy)
	if l > 0 {
		n += 1 + l + sovPosts(uint64(l))
	}
	l = len(m.SortOrder)
	if l > 0 {
		n += 1 + l + sovPosts(uint64(l))
	}
	l = len(m.ParentID)
	if l > 0 {
		n += 1 + l + sovPosts(uint64(l))
	}
	if m.CreationTime != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreationTime)
		n += 1 + l + sovPosts(uint64(l))
	}
	l = len(m.Subspace)
	if l > 0 {
		n += 1 + l + sovPosts(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovPosts(uint64(l))
	}
	if len(m.Hashtags) > 0 {
		for _, s := range m.Hashtags {
			l = len(s)
			n += 1 + l + sovPosts(uint64(l))
		}
	}
	return n
}

func sovPosts(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPosts(x uint64) (n int) {
	return sovPosts(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Post) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPosts
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Post: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Post: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PostID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParentID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParentID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Created", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.Created, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastEdited", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.LastEdited, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowsComments", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AllowsComments = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subspace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subspace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OptionalData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OptionalData = append(m.OptionalData, OptionalDataEntry{})
			if err := m.OptionalData[len(m.OptionalData)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attachments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attachments = append(m.Attachments, Attachment{})
			if err := m.Attachments[len(m.Attachments)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PollData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PollData == nil {
				m.PollData = &PollData{}
			}
			if err := m.PollData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPosts(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPosts
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPosts
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Attachment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPosts
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Attachment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Attachment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field URI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.URI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MimeType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MimeType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tags = append(m.Tags, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPosts(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPosts
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPosts
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OptionalDataEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPosts
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OptionalDataEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OptionalDataEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPosts(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPosts
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPosts
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPostsParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPosts
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPostsParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPostsParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SortBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SortBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SortOrder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SortOrder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParentID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParentID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreationTime == nil {
				m.CreationTime = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CreationTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subspace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subspace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hashtags", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hashtags = append(m.Hashtags, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPosts(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPosts
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPosts
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPosts(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPosts
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPosts
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPosts
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPosts
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPosts
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPosts        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPosts          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPosts = fmt.Errorf("proto: unexpected end of group")
)
